### ISSUE TITLE
Serverless Symfony on AWS Lambda

### ISSUE THREAD

**Issue by svenfinke** [phpugms/talks#21]
## Talk description
I'd like to show you how to setup a monolithic symfony application as a serverless function in AWS Lambda. I'll probably also setup services like RDS (Databases) and ElastiCache (Managed Redis Cluster) and connect them to the Lambda function, talk about downsides and limitations and how they could be solved.

## Talk length (in Minutes)
This can vary depending on what you want to see. But a main talk with 45-60 minutes could be a good idea.

## Preferred language
No preference.

- [x] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time
(You can find all our upcoming events here: https://www.meetup.com/phpugms/events/)

- March or May

## Speaker names
(Please name all speakers giving this talk.)

- Sven Finke

## Speakers info
(Optional, your company, your position, etc.)

- Shopware AG, DevOp @ Team Enterprise

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugms)

- https://twitter.com/svenfinke

**Comment by bcremer** [comment]
@svenfinke Thanks for your Talk, that's a fantastic proposal. Looking forward hearing it.

As for the date, the upcoming meetup dates are:

- Wednesday, March 20, 2019
- Thursday, April 18, 2019
- Monday, May 20, 2019


The March Meeting is currently blocked by https://github.com/phpugms/talks/issues/20 from @ndzoesch.
Feel free to talk to @ndzoesch if you two want to change dates etc.

Otherwise please let me know if Monday, May 20, 2019 is good for you.

**Comment by bcremer** [comment]
@svenfinke I have scheduled your talk for Monday, May 20, 2019.
